branch-defaults:
  master:
    environment: Shoesstore-Webservice-env
environment-defaults:
  Shoesstore-Webservice-env:
    branch: null
    repository: null
global:
  application_name: ShoesStore
  default_ec2_keyname: Intern
  default_platform: arn:aws:elasticbeanstalk:ap-southeast-1::platform/Docker running
    on 64bit Amazon Linux/2.12.14
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
