version: 2
jobs:
  deploy:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run:
          name: Install EB CLI
          command: |
            sudo pip install awsebcli --upgrade
      - run:
          name: Deploy to EB if branch is Master
          command: |
            eb deploy Shoesstore-Webservice-env

workflows:
  version: 2
    jobs:
      - deploy:
        filters:
          branches:
            only:
              -master
