version: 2
jobs:
  deploy:
    docker:
      - image: python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install EB CLI
          command: |
            pip install awsebcli
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
      - run:
          name: Deploy to EB if branch is Master
          command: |
            eb use Shoesstore-Webservice-env --profile eb-cli
            eb deploy Shoesstore-Webservice-env

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
